### PR TITLE
плюшки ватрушки!

### PR DESCRIPTION
**Pull request by Kenshut**
Добавляю различные "плюшки-ватрушки"

Краткое содержание:
Добавление места "последнего боя"
Добавление условия "категория оружия в руках"
Обновление айди-шника для компилирование сборки windows msvc
Разнообразие концовок-мира для НПС
Слабые точки триффидов и описание при разделке
Слабые точки грибов и описание при разделке
Слабые точки слизи

Портировал из:
https://github.com/CleverRaven/Cataclysm-DDA/pull/68458
https://github.com/CleverRaven/Cataclysm-DDA/pull/68044
https://github.com/CleverRaven/Cataclysm-DDA/pull/69592
https://github.com/CleverRaven/Cataclysm-DDA/pull/69758
https://github.com/CleverRaven/Cataclysm-DDA/pull/69764
https://github.com/CleverRaven/Cataclysm-DDA/pull/69700
https://github.com/CleverRaven/Cataclysm-DDA/pull/69583

### CODE REVIEW

**Comment by RenechCDDA** [comment]
@AtomicFox556 This appears to be a copy of https://github.com/CleverRaven/Cataclysm-DDA/pull/68458 (authored by @NetSysFire) and https://github.com/CleverRaven/Cataclysm-DDA/pull/69156 (authored by @detahramet, @TheShadowFerret, and @Termineitor244) without attribution.

**Comment by Kenshut** [comment]
@RenechCDDA You are absolutely right, we are just manually transferring the changes from dda, since atomic fox has been refusing to make a pull request directly from dda since August, since there is an unpleasant update there as far as I remember

**Comment by NetSysFire** [comment]
"just manually transferring the changes" does not justify giving no attribution whatsoever. You are still bound by the upstream license, which requires attribution.

**Comment by AtomicFox556** [comment]
> @AtomicFox556 This appears to be a copy of [CleverRaven#68458](https://github.com/CleverRaven/Cataclysm-DDA/pull/68458) (authored by @NetSysFire) and [CleverRaven#69156](https://github.com/CleverRaven/Cataclysm-DDA/pull/69156) (authored by @detahramet, @TheShadowFerret, and @Termineitor244) without attribution.

Noted, thanks.


> "just manually transferring the changes" does not justify giving no attribution whatsoever. You are still bound by the upstream license, which requires attribution.

What would you consider sufficient attribution, just to avoid further misunderstandings?

**Comment by andrei8l** [comment]
> What would you consider sufficient attribution, just to avoid further misunderstandings?

The original author(s) and emails need to be listed in the commit message. Ideally you accomplish that by cherry-picking the original commits. The lazy, but still acceptable, way is to add `Co-authored-by: NAME <NAME@EXAMPLE.COM>` to the bottom of the commit message. Github has some information about that [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

Since this PR hasn't been merged yet, I strongly recommend that you redo it by cherry picking and adding your modifications in a separate commit.

For [#130](https://github.com/AtomicFox556/Cataclysm-EOD/pull/130/files) the easiest way would be to start with an interactive rebase, then amend every commit with the correct authorship, and finally force-push to the repo. There are many guides on stackoverflow for that.

**Pull request merged**
